services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app-network
  caddy:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      #- "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
